### ISSUE TITLE
[NEW SECTION] add instructions on how to debug C++ code

### ISSUE THREAD

**Issue by Bai-Li-NOAA** [NOAA-FIMS/collaborative_workflow#103]
**Title of section**
C++ debugging

**Suggested section content and location**
How to debug C++ code using GDB and std::ofstream out("debug.txt")

**Additional context**
This section could be added to [10-testing.Rmd](https://github.com/NOAA-FIMS/collaborative_workflow/blob/main/10-testing.Rmd) file.

**Comment by iantaylor-NOAA** [comment]
gdb info added by @Bai-Li-NOAA in 4c180c57ab6526e510bb95f2e72ba0faaa2981aa. 
We could still benefit from a note adding things like `std::ofstream out("debug.txt")`.

**Comment by kellijohnson-NOAA** [comment]
There are currently instructions in the collaborative workflow for `ofstream` here
https://github.com/NOAA-FIMS/collaborative_workflow/blob/dcda6b1641e9fe7390e47a001ec63a5c62e3a5e8/10-testing.Rmd#L354-L360

So, I think we can close this issue. But I will leave that up to @Bai-Li-NOAA and @iantaylor-NOAA.

**Comment by Bai-Li-NOAA** [comment]
Thank you, @kellijohnson-NOAA for finding the documentation. I agree that we can close the issue.
