### ISSUE TITLE
[NEW SECTION] Revise governance section

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/collaborative_workflow#105]
**Title of section**
Lead of Accessibility and Workflows? Please edit @k-doering-NOAA 

**Suggested section content and location**
We are missing Kathryn's role, and I also think some other governance items can be revised as we go through the process and learn how to function more effectively as a team.

**Additional context**

**Comment by kristanblackhart-NOAA** [comment]
I think Kathryn's role is intended to be more expansive than accessibility and workflows, especially as we move beyond M1. We've talked about linkages to FIT and multidisciplinary tools.
