### ISSUE TITLE
[BUG] workflow doc doesn't follow the rebase workflow we want to use

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/collaborative_workflow#106]
**Describe the bug**
We've been merging main into feature branches and this results in a very messy commit history - we are going to move to rebasing instead

**To Reproduce**
Update your feature branch
Update main

**Expected behavior**
The user rebases the changes from main into their branch and does not use pull and merge

**Comment by kellijohnson-NOAA** [comment]
- [ ] Find a link to a good rebase tutorial
- [ ] Revise the instructions in the following section
https://github.com/NOAA-FIMS/collaborative_workflow/blob/dcda6b1641e9fe7390e47a001ec63a5c62e3a5e8/07-contributor-guide.Rmd#L220
- [ ] Add Git Hooks (client and server) to stop all pushes where main is merged into a feature branch
- [ ] Notify all contributors that main should not be merged into feature branches

**Comment by kellijohnson-NOAA** [comment]
Some good guidance was brought out in the research conducted for [seaside chat 4](https://github.com/NOAA-FIMS/seaside-chats/issues/4#issuecomment-2187236147).
