### ISSUE TITLE
automatically building developers handbook

### ISSUE THREAD

**Issue by k-doering-NOAA** [NOAA-FIMS/collaborative_workflow#11]
I set up a first version of a bookdown workflow: https://github.com/NOAA-FIMS/collaborative_workflow/blob/main/.github/workflows/update-bookdown.yml

I had some questions about how it should be set up.

1. I think a cleaner solution might be deploy the output to a separate branch (perhaps called gh-pages by convention). This eliminates the need to commit output directly to the main branch. I started doing this for the SSMSE manual and have liked it better. Here is what the SSMSE gh-pages branch looks like: https://github.com/nmfs-fish-tools/SSMSE/tree/gh-pages .Basically, it is just the rendered content. Let me know if we should set it up this way!

2. If we like the way the rendering is currently set up (committing the rendered bookdown to the docs folder directly), that is fine - or now, I am setting it up to open a pull request, but we could set it up to automatically commit. I thought it would be good to test it out first with the pull request

**Comment by ChristineStawitz-NOAA** [comment]
Thanks @k-doering-NOAA ! I think it depends on how we want to use this collaborative_workflow repo. I don't see a problem with folks committing directly to main (and might make things easier for the git newbies) if all this repo contains is the handbook (unlike `SSMSE` which has code too). but if we want to have this repo house other content, it makes sense to set up a gh-pages branch.

**Comment by k-doering-NOAA** [comment]
Ok! To be clear, it's just the github action committing to gh-pages, not people. The difference is whether rendered content is in the main branch git history or not

I can leave it as-is for now (the github opens a pull request that can be merged to main), but we can reevaluate later if it should be changed.

**Comment by ChristineStawitz-NOAA** [comment]
@k-doering-NOAA a dumb question as I'm actually using this workflow now - how do you view the rendered book before merging in the pull request? Maybe this is why you suggested using the `gh-pages` workflow instead?

**Comment by k-doering-NOAA** [comment]
No, this is a good point - I suppose you could checkout the branch and look in the browser locally?

With the gh-pages workflow, it still doesn't provide an easy way to "preview" before publishing, but you don't have to commit the rendered content like you do with this workflow (by merging in).

There probably is a way to have a "development" webpage for previewing the changes more easily, but I'm not sure how to do this.
