### ISSUE TITLE
add info on radian install

### ISSUE THREAD

**Issue by k-doering-NOAA** [NOAA-FIMS/collaborative_workflow#110]
To install radian on windows, I had to use the command

```py
py -m pip install "radian"

```

Which is a little different than the instructions on the [radian readme](https://github.com/randy3k/radian#installation). We should note this in the collaborative workflow doc. 

I found this reference helpful: https://packaging.python.org/en/latest/tutorials/installing-packages/#installing-packages

This also looks helpful: https://github.com/REditorSupport/vscode-R/wiki/Installation:-Windows#radian

**Comment by kellijohnson-NOAA** [comment]
radian is not required to run FIMS. I suggest that we do not add this to the collaborative_workflow and instead, when we end up finding a NOAA/NMFS-wide location for this type of great information that we place it there.
