### ISSUE TITLE
Move User Guide from Collaborative Workflow to vignette

### ISSUE THREAD

**Issue by iantaylor-NOAA** [NOAA-FIMS/collaborative_workflow#117]
The User Guide https://noaa-fims.github.io/collaborative_workflow/user-guide.html would be more visible if it were a vignette on the main FIMS pkgdown site: https://noaa-fims.github.io/FIMS/. 

This was identified as a need at the 2023 in-person workshop as noted at the bottom of https://docs.google.com/document/d/17HemqP0hwcZ16ZiMHDYkBB9Gz4XUZPGMycWmPooivNc/edit#task=Ly-B3_BIwUascXSj.

**Comment by iantaylor-NOAA** [comment]
@k-doering-NOAA and @kellijohnson-NOAA, thanks for all your work improving and reorganizing info for developers and users in #146 and other places. Is there anything valuable in https://noaa-fims.github.io/collaborative_workflow/user-guide.html or should that section just be deleted to close this issue (which I self assigned months ago but let languish)?

**Comment by k-doering-NOAA** [comment]
@iantaylor-NOAA thanks for the reminder about this one! 

It is basically just the installation instructions now. Perhaps after we merge in https://github.com/NOAA-FIMS/collaborative_workflow/blob/codespaces/04-user-guide.Rmd, you can decide if it should just link to the vignette instead (or be deleted altogether)? The install instructions are also on the FIMS readme, so it's a bit duplicative.

**Comment by kellijohnson-NOAA** [comment]
Thanks @iantaylor-NOAA for reaching out. My vote would be to delete the section and ensure that the users are supported through the README on NOAA-FIMS/FIMS and vignettes located there as well.

**Comment by k-doering-NOAA** [comment]
Sounds good! @kellijohnson-NOAA , feel free to delete the section in https://github.com/NOAA-FIMS/collaborative_workflow/tree/codespaces
