### ISSUE TITLE
figure out some big picture documentation questions and workflows

### ISSUE THREAD

**Issue by iantaylor-NOAA** [NOAA-FIMS/collaborative_workflow#118]
Create a small group to do the following
* Consider using [agile philosophy](https://agilemodeling.com/essays/agiledocumentation.htm)
* Define how to create a triage / tracking system
* Define terms related to documentation because we have different groups of documentation, e.g., doxygen, roxygen, installation guide, etc.

This need was identified during the 2023 FIMS in-person workshop (noted at https://docs.google.com/document/d/17HemqP0hwcZ16ZiMHDYkBB9Gz4XUZPGMycWmPooivNc/edit#task=ZVSxA6N8cb01p6vg).

**Comment by Bai-Li-NOAA** [comment]
The documentation group has created a [documentation table](https://docs.google.com/document/d/1tPCSSanZ7SHaSE5SMkPoYrZh_lsswe7o5gtEyJmA0DU/edit#heading=h.aotl90l7zra0) to describe individual types of documentation. We need to 

- [ ] publish the documentation table on FIMS repo
- [ ] use the power of markdown to publish a subset of the table, as users may not be interested in some columns
- [ ] reorder the rows and put user guides at the top of the table

**Comment by iantaylor-NOAA** [comment]
Nice work @Bai-Li-NOAA, I think the format you chose works really well.

Here are a few minor changes that occur to me:
1. It would be easier to skim through the list if the names of the documentation types were more different from the sub-bullets, such as via all-caps or larger font.
2. It might be better to default to the "Documentation for user" tab since they are the ones who will be least familiar with the documentation options and it would make the list shorter. On the other hand, at this stage it's mostly developers who will be looking at this right now so maybe it's good to remind us of all the things we need to look at and maintain.
3. The "Requirements" section seems like it should just be for developers, not users

**Comment by Bai-Li-NOAA** [comment]
Thanks @iantaylor-NOAA. All suggestions have been addressed.
