### ISSUE TITLE
add diagrams using mermaid where useful

### ISSUE THREAD

**Issue by iantaylor-NOAA** [NOAA-FIMS/collaborative_workflow#121]
@MOshima-PIFSC, @k-doering-NOAA and I discussed mermaid diagrams in the context of a design document for FIMS output today.

Here's a potential flow for this work:
```mermaid
graph TD;
    A[learn mermaid];
    B[keep an eye out for places\n where diagrams will be helpful];
    A-->C[add mermaid diagrams in those places];
    B-->C;
```
That diagram above was rendered automatically within this github issue from the code below (displayed below as code using [4 backticks](https://yihui.org/en/2017/05/four-backticks-github/https://yihui.org/en/2017/05/four-backticks-github/)--another useful thing I learned today)

````
```mermaid
graph TD;
    A[learn mermaid];
    B[keep an eye out for places\n where diagrams will be helpful];
    A-->C[add mermaid diagrams in those places];
    B-->C;
```
````

A few resources: 
* mermaid website: https://mermaid.js.org/
* live editor (for sandboxing stuff, but can also work by using Preview within a github issue): https://mermaid.live/

**Comment by iantaylor-NOAA** [comment]
I see a drawback of using the diagrams in github issues is that email notifications don't render the diagrams in the same way as they do on the github website.

**Comment by k-doering-NOAA** [comment]
@iantaylor-NOAA that's so cool that on GitHub they are automatically rendered and that you can preview them! The live editor was nice for collaborative editing without needing to switch back and forth between write and preview views on github

**Comment by Bai-Li-NOAA** [comment]
We can add detailed instructions in the collaborative book if R user group find this diagram useful.

**Comment by kellijohnson-NOAA** [comment]
Because we are using .Rmd files in the workflow website, the mermaid graph does not render. See [these lines](https://github.com/NOAA-FIMS/collaborative_workflow/blob/225b4f2d8d5087bdcc27ae66f1925d443920b673/02-FIMS-Project-Overview.Rmd#L168-L179). It needs to be wrapped in `DiagrammeR::mermaid()` according to [this stackoverflow chat](https://stackoverflow.com/questions/40803017/how-to-include-diagrammer-mermaid-flowchart-in-a-rmarkdown-file). Fixed with  e8ca014.

**Comment by kellijohnson-NOAA** [comment]
@iantaylor-NOAA can we close this issue given that there are no proposed diagrams to add at the moment?

**Comment by iantaylor-NOAA** [comment]
@kellijohnson-NOAA, thanks for fixing the broken render and suggesting closing the issue.
The goal of this issue was to raise awareness of the option to use mermaid and that has been achieved.
