### ISSUE TITLE
Revision Table

### ISSUE THREAD

**Issue by msupernaw** [NOAA-FIMS/collaborative_workflow#14]
We need to add a version/revision table

**Comment by kristanblackhart-NOAA** [comment]
Is there a way to do this other than manual updates?

**Comment by kristanblackhart-NOAA** [comment]
Currently the date that the document was last updated is displaying on the first page of the document. Once we have a complete version of the document in place and aren't making such rapid commits, we will begin using releases to keep track of versions as well. This seems sufficient; I don't see the need for a revision table in the document itself.
