### ISSUE TITLE
code review process

### ISSUE THREAD

**Issue by kristanblackhart-NOAA** [NOAA-FIMS/collaborative_workflow#17]
Thoughts on process for assigning code reviewer? e.g. auto, round robin, load balance

I like load balance (chooses reviewers based on each member's total number of recent review requests and considers the number of outstanding reviews for each member). 

More here: https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team

**Comment by k-doering-NOAA** [comment]
This is cool, @kristanblackhart-NOAA , I had no idea these were options! 

I like the load balance one, too. I'm wondering what your thoughts are if there is an obvious choice of reviewer due to their specialty - will the person making the PR also be able to assign a reviewer manually? Or alternatively will people be able to turn down a review if they feel they don't have the expertise?

**Comment by cmlegault** [comment]
Thanks @kristanblackhart-NOAA for suggesting this approach. I'm with @k-doering-NOAA in that I was not aware such an automated process existed.

One challenge for the approach is the reality that FIMS folks have other tasks and that those at times will be all-consuming (e.g. stock assessment due). As long as we can find a way to deal with these additional constraints, I'm all for the approach suggested.

**Comment by kristanblackhart-NOAA** [comment]
@k-doering-NOAA  I think specific reviewers can be assigned and then the automatic assignment kicks in if nobody has been assigned, but I will confirm that. 

@cmlegault People can set their status to busy (e.g. stock assessment crunch time) and the assignment algorithm will skip them. 

It's a pretty smart system, but the issue @k-doering-NOAA raises about people turning down a review based on expertise needs to be addressed. Let me look into that some more.

**Comment by kristanblackhart-NOAA** [comment]
Text is complete in Ch. 3 of contributor guide. Let me know if you have any further comments, and thanks for your input.
