### ISSUE TITLE
Create a way to visualize progress

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/collaborative_workflow#35]

**Comment by ChristineStawitz-NOAA** [comment]
This is now tracked on the `README` but still a work in progress

**Comment by k-doering-NOAA** [comment]
Could using milestones on github and the progress bar as issues are closed out serve this purpose?

https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones

**Comment by iantaylor-NOAA** [comment]
Linking to a specific `README` (hopefully the one that @ChristineStawitz-NOAA is referencing two comments above): 
https://github.com/NOAA-FIMS/FIMS#readme
which currently shows the following table to visualize progress
![image](https://user-images.githubusercontent.com/4992918/151243744-003f76ec-653f-4d6c-a9ac-6117bef853c6.png)

**Comment by ChristineStawitz-NOAA** [comment]
I moved this to noaa-fims.github.io repository with the goal of rendering it to HTML via jekyll so you don't have to look at the github page to see it https://noaa-fims.github.io/status/ but still working on best ways of visualizing
