### ISSUE TITLE
Flesh out FIMS governance page

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/collaborative_workflow#36]

**Comment by ChristineStawitz-NOAA** [comment]
I just pushed some updates to https://noaa-fims.github.io/collaborative_workflow/fims-governance.html (should render soon). Close if this is good or let me know what else you'd like to see on this page.

**Comment by JonBrodziak** [comment]
In section 4.5, can you provide an example of "everyday development"?
This is not exactly a clear spec, my $0.02.

**Comment by ChristineStawitz-NOAA** [comment]
Thanks for the feedback Jon - I will add an example of "everyday development." Would love more details about what else I can do to improve clarity throughout.

**Comment by ChristineStawitz-NOAA** [comment]
fixed in https://noaa-fims.github.io/collaborative_workflow/fims-governance.html#external-collaborators
