### ISSUE TITLE
[NEW SECTION] Software specification

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/collaborative_workflow#42]
**Title of section**
Software specification

**Suggested section content and location**
This will describe the modules in FIMS milestone 1 and how each of the components are implemented. We will start by focusing on the C++ implementation and then bring in more detail about the R functionality

**Additional context**
Will move content from https://docs.google.com/document/d/1iSEhJqcpSD269QdABeDE4aBZGqGcBrIrLnS7eMkSYv0/edit#heading=h.70perzbxm1pd to define closed design issues.

**Comment by iantaylor-NOAA** [comment]
M1 specifications are documented and will be tagged as M1 (see https://github.com/NOAA-FIMS/collaborative_workflow/issues/116). Will open new issue for need to update to MQ and then M2.
