### ISSUE TITLE
Reach out to Kasper re: how to track and manage TMB dependencies and breaking changes

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/collaborative_workflow#45]

**Comment by ChristineStawitz-NOAA** [comment]
@Andrea-Havron-NOAA brought up the switch within `TMB` to `TMBad` and it made us think about how we track the `TMB` testing process and ensure the team is aware of breaking changes. If we are going to explicitly depend on `TMB` software will probably need to keep closer tabs on when things change and whether the testing process is up to our standards.

**Comment by Cole-Monnahan-NOAA** [comment]
Agree this is important. I think at a minimum we should configure the CI testing framework to run on development branches of TMB so we can catch it early. Probably good to have a running conversation with Kasper about future changes.

What makes FIMS different from other dependent packages like VAST or WHAM? Does the modularity approach make things more or less resilient to changes?

**Comment by ChristineStawitz-NOAA** [comment]
Yeah, ideal dependency management is to ensure a version/branch of `TMB` is reliable, then freeze that version to develop on until some planned, scheduled new release at which point we test FIMS on the new release of `TMB` extensively before porting it over and making an announcement. Right now, I don't have confidence the most recent posted release on the `TMB` github site is the one we should be using as its two years old. It would be good to check that Kasper's use of semantic versioning is in line with what we would expect.

I would also like to make it a two-way conversation as I would hope if we have need for say, a new atomic function that could be useful to other `TMB` models we could do that via a pull request to `TMB`.

My goal is to make installation more predictable than it is with VAST through a more restricted process for incorporating and tracking dependencies.

**Comment by kellijohnson-NOAA** [comment]
I really like that WHAM documents which version (commit) was used wrt TMB and WHAM, e.g.,
![summary_text](https://user-images.githubusercontent.com/4108564/153092960-16a8561c-c7ff-4ddb-a31e-43f2673bdbef.png)

**Comment by Cole-Monnahan-NOAA** [comment]
OK I emailed Kasper to start a discussion about it

**Comment by Andrea-Havron-NOAA** [comment]
Thanks Cole! Can you loop me into the discussion as well?

**Comment by ChristineStawitz-NOAA** [comment]
Reflagging this since we have an open bug caused by `TMB`. I'm sure this will not be the last time, so it would be good if we got from Kasper how he would like us to track and notify him of breaking issues and potentially fix them ourselves and open a pull request? To my knowledge there is not a contributors guide but please correct if I'm wrong about that.

**Comment by Cole-Monnahan-NOAA** [comment]
I bumped Kasper to see if he will respond. I guess I could tag him here if you'd rather do that?

**Comment by Cole-Monnahan-NOAA** [comment]
Here's what Kasper said:

>  Let me give some background to help you asses the real risk of TMB breaking downstream dependencies.
> As you probably know there's a fairly comprehensive test suite run on every commit to the TMB repository. The full suite is run independently for each of the two AD frameworks (CppAD/TMBad). The test consists of (1) normal R CMD check (2) Correctness of all tmb_examples (3) Compilation of selected downstream projects (glmmTMB, VAST, FIMS in the future?...) (4) other tests including simulators, special function derivatives checking doxygen documentation etc.
> In addition every submission of TMB to CRAN is subject to CRAN's downsteam dependencies checks on a wide range of platforms.
> 
> Learning from past experience, problems triggered by the tests have almost exclusively been caused by upstream projects, notably:
> 
> - CppAD
> - Eigen (On CRAN via 'RcppEigen')
> - The Matrix package
> - R devel
> - Compiler changes (mainly clang)
> 
> CppAD is frozen inside TMB and a don't plan to update it ever again. All the rest is out of control.
> 
> To minimize issues caused by upstream packages I therefore recommend to use a fairly recent TMB version for development of FIMS.
> If you need a 'production' stable version of FIMS I'd suggest freezing all the above packages, not just TMB (perhaps using docker containers or something similar).
> 
> In general I wouldn't be worried that future versions of TMB will break FIMS. But here some random thoughts to minimize problems:
> 
> - avoid using the newest TMB features
> - run tests with both AD frameworks on several platforms
> - add TMB_SAFEBOUNDS to compilation
> - put helper functions in FIMS namespace to avoid name clashing (e.g. what happens if 'dlognorm' is added to TMB?).
> 
> There's probably more that I don't remember... Hope this answers at least some of the questions.

It's probably easier to tag him here if we have follow up questions so it's more public.

**Comment by ChristineStawitz-NOAA** [comment]
Thanks, this is good to know. Right now in the `FIMS` `DESCRIPTION` I am requiring a version of `TMB` more recent than 1.7.14 but we could follow the repo to update that to the latest version whenever there is a new stable release (major or minor semantic version number?)

This doesn't answer the other ongoing question which is what to do when we do find a blocking issue for `FIMS` in `TMB` as is currently happening with TMB's `isnan` function masking the one from `cmath`. Is it preferred to open an issue in the TMB repo, open a pull request with a fix, email?

**Comment by Andrea-Havron-NOAA** [comment]
I followed up with Kasper about this.

**Comment by Andrea-Havron-NOAA** [comment]
I emailed Kasper about these issues before seeing Cole's note about tagging him directly in this thread. I agree with Cole - that is probably the best approach moving forward.

Kasper's response:

> Regarding TMB versions they are officially available on the CRAN page:
> https://cran.r-project.org/web/packages/TMB/index.html
> Current version is as you can see 1.8.1 and older versions are in 'TMB archive'. 1.8.0 would be a reasonable requirement.
> I recommend keeping an eye on the NEWS file which gives a very brief overview of each version. Often there's a link to a github issue to give more details on what was fixed:
> https://cran.r-project.org/web/packages/TMB/NEWS
> Since version 1.7.14 a lot has changed. Some of the changes are super critical (which I admit isn't always obvious from the description). Watch out for 'ASAN issues' and 'header issues with the Matrix package'!
> As mentioned earlier those critical bugs are always triggered by something outside of my control. My general strategy is to fix TMB in a way that makes it work even if the bug in the upstream project is present. It follows that the higher version number of TMB the higher is its immunity to problems in upstream projects.
> On the other hand, as with all software, a higher version number also means a risk of breaking things. For instance if I added a new function 'dlognorm' to TMB and another user already had a function of that name in a model, TMB would break the model. That brings me to your second question. I generally prefer a prior discussion about potential side effects on the github issue tracker before receiving pull requests.
> I seem to recall Matthew's issue was about using Rcpp and TMB in the same compilation unit? That's not (yet) an officially supported feature of TMB and can thus not be characterized as a bug :) A reproducible example sent to the issue tracker would be the preferred first step.

**Comment by k-doering-NOAA** [comment]
I think this has been resolved given conversations re TMBad and the cmath issue (fixed by changing the order that libraries are loaded), but feel free to reopen if needed.
