### ISSUE TITLE
[NEW SECTION]: add in a section for software setup for FIMS

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/collaborative_workflow#47]
**Title of section**
software specs

**Suggested section content and location**
Wishlist for software setup doc: (1) recommended VScode extensions, (2) steps to setup C++ compiling in VScode, (3) steps to setup R terminal (w or w/o radian)
I can google all those things, but would be better for us to build a shared doc
https://www.r-bloggers.com/2021/01/setup-visual-studio-code-to-run-r-on-vscode-2021/

**Comment by iantaylor-NOAA** [comment]
Wishlist above was from chat during VSCode meeting. Similar info would be welcome for all the other software tools that we'll be using (list below modified from Feb 16 meeting notes):
- Integrated development environment
  - Rstudio 
  - VS code
  - Other IDEs?
- Testing framework
  - already in [FIMS doc](https://noaa-fims.github.io/collaborative_workflow/test-case-template.html)
- C++ compiler 
- R/Rtools40/TMB

Also, might be good to note for each tool if there are folks with expertise who are willing to act as a helpdesk.

**Comment by ChristineStawitz-NOAA** [comment]
added this section and will track new additions in issue #50
