### ISSUE TITLE
Implement relevant parts of https://codebender.org/

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [NOAA-FIMS/collaborative_workflow#5]
[Code Bender](https://codebender.org/) has a great training program on how to manage a Research Software Project. 
- [x] https://merely-useful.tech/py-rse/
- [x] [Governance](https://codebender.org/governance/)
- [x] [Communication](https://codebender.org/communication/)
- [x] [Workflow](https://codebender.org/workflow/)
- [x] [Newcomers](https://codebender.org/newcomers/)
- [x] [Design](https://codebender.org/design/)
- [x] [Mechanics](https://codebender.org/mechanics/)
- [ ] [Leadership](https://codebender.org/leadership)
- [ ] [Change](https://codebender.org/change)
- [ ] [Software Engineering](https://codebender.org/engineering/)
- [ ] [Robustness](https://codebender.org/robustness/)
- [ ] [Partnering](https://codebender.org/partnering/)
- [ ] [Findability](https://codebender.org/findability/)

**Comment by cmlegault** [comment]
A nice checklist for pull requests is available [here](https://sourcelevel.io/pull-requests-checklists-metrics-and-best-practices-a-definitive-guide).

**Comment by Bai-Li-NOAA** [comment]
Thanks for sharing the links. I am closing the issue since there are no further tasks.
