### ISSUE TITLE
clarifications to sections related to C++ compilers, C++ testing and debugging, and the development environment

### ISSUE THREAD

**Issue by JaneSullivan-NOAA** [NOAA-FIMS/collaborative_workflow#50]
For VSCode's recommended C/C++ extension, [blog posts](https://gourav.io/blog/setup-vscode-to-run-debug-c-cpp-code) for Windows users recommend having the MinGW64 installed and on your C drive (and proper path C:\MinGW64\bin). In the development environment section of the FIMS handbook, it says Rtools is sufficient and I know I have gcc on my machine through admb and the mysys2 version of mingw64 through rtools40.

I'm just confused about what exactly I need and if I can use the compilers already on my machine to use VSCode's C/C++ extension to compile programs and debug.

TIA

**Comment by ChristineStawitz-NOAA** [comment]
Yes, you should be able to use the compiler in mysys2. I just added instructions how to add it to your path without going through IT (hopefully) here: https://noaa-fims.github.io/collaborative_workflow/software-developer-guide.html#c-compiler

Let me know if this works!
