### ISSUE TITLE
Add in a github action to knit bookdown and save as artifact

### ISSUE THREAD

**Issue by k-doering-NOAA** [NOAA-FIMS/collaborative_workflow#52]
**Is your feature request related to a problem? Please describe.**
Currently, there is no check that bookdown is able to knit upon changes if working in a branch

**Describe the solution you'd like**
Add a github action that knits bookdown and stores the html files (or maybe pdf?) as an artifact. 

**Describe alternatives you've considered**
Alternatively, we could just tell folks to render locally, but I think having an automated check is nice. Plus, having a rendered version for reviewers of the pull request can be helpful

**Additional context**

I can work on this, unless someone else would like to! It would probably good to make this a reusable workflow in the nmfs-fish-tools/ghactions4r instead of making a custom action in this repository.

**Comment by iantaylor-NOAA** [comment]
I couldn't find the artifact associated with PR #75. The GitHub Action says bookdown ran and the artifact was uploaded, but I'm not seeing it (maybe I'm just missing something simple):
https://github.com/NOAA-FIMS/collaborative_workflow/actions/runs/2019351553

**Comment by iantaylor-NOAA** [comment]
Sorry, cancel that. Found it now. My fault.
