### ISSUE TITLE
FIMS license

### ISSUE THREAD

**Issue by k-doering-NOAA** [NOAA-FIMS/collaborative_workflow#55]
**Title of section**
Software License

**Suggested section content and location**
This should make clear which license FIMS is under (any maybe why?) It also should include any hoops contributors might have to go through to get their code into the codebase (e.g., for the shiny R package, you have to sign some sort of release before your PR is merged in if you aren't a primary developer).

**Additional context**
I saw in the FIMS code repo that GPL3  is the current license choice. I'm curious if this has been discussed and clearly chosen? GPL3 is more restrictive than MIT (although they are both open source licenses), so I was surprised to see it, but perhaps there is a good reason for it?

**Comment by ChristineStawitz-NOAA** [comment]
per discussion with @k-doering-NOAA I don't think we have a better answer than this until the NAO software governance group gives more guidance, so closing for now
