### ISSUE TITLE
[BUG] Need to reorganize the doc periodically to keep filenames in sync and separate out sections

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/collaborative_workflow#56]
**Describe the bug**
@Andrea-Havron-NOAA pointed out it is hard to navigate the Rmd files and separating out high level and more cookbook sections.

**Expected behavior**
Separate overview and how to sections.

**Comment by Andrea-Havron-NOAA** [comment]
I will be using this [branch](https://github.com/NOAA-FIMS/collaborative_workflow/tree/doc-restructure) to restructure the document

**Comment by Andrea-Havron-NOAA** [comment]
I have pushed changes up to the [doc-restructure](https://github.com/NOAA-FIMS/collaborative_workflow/tree/doc-restructure) branch. Hyperlinks will need to be checked and fixed but it would be great to get feedback on the reorganization of the book before taking that step.

**Comment by ChristineStawitz-NOAA** [comment]
I'm going to close this and open a pull request to merge in doc-restructure. I merged the changes to main into the `doc-restructure` branch to clean things up before addressing other content requested. It all looks good to me!
