### ISSUE TITLE
minor revisions to R-related elements of software installation guide

### ISSUE THREAD

**Issue by iantaylor-NOAA** [NOAA-FIMS/collaborative_workflow#61]
The paragraph on user software install contains a lot: https://github.com/NOAA-FIMS/collaborative_workflow/blob/9f97426e228cf51c65ac45a03090c836c1fced34/04-user-guide.Rmd#L12

Here are a few suggested revisions based on a planning session for the R Packages training that @k-doering-NOAA and I are working on:
- reformat as a bulleted list and only include OS-specific info under the relevant systems
- require R version 4.0.0 via a change to the https://github.com/NOAA-FIMS/FIMS/blob/main/DESCRIPTION and simply state that as a requirement in this guide
- clarify that that RStudio isn't a requirement (while still noting that version 1.2.5042 or newer is needed if you choose to use it)
- note that the `remotes` package is needed, or recommend installing `devtools` which comes with remotes
- Rtools may be the only thing that needs to go under `Windows users`, and there clarify that IT support is needed to install it on NOAA computers (or any without administrative accounts)

I'm happy to put together a Pull Request, but wanted to offer other the opportunity for input instead of just assuming the choices are the best ones

**Comment by k-doering-NOAA** [comment]
These all make sense to me! @iantaylor-NOAA!

Maybe edits also need to be made to https://noaa-fims.github.io/collaborative_workflow/developer-software-guide.html in advance of the workshop (e.g., requiring a specific R version, perhaps including instructions on how to clone the FIMS repo)

**Comment by Andrea-Havron-NOAA** [comment]
@k-doering-NOAA, there is a placeholder section in the [Contributers guidelines](https://noaa-fims.github.io/collaborative_workflow/contributor-guidelines.html#github-forking-and-cloning) chapter on how to fork/clone the repo. I know that @Bai-Li-NOAA will be providing instructions on git workflows during her training session Monday, but probably good still to get a bit more detail in the collaborative workflow document before the workshop.
