### ISSUE TITLE
conventions for naming files, tests

### ISSUE THREAD

**Issue by k-doering-NOAA** [NOAA-FIMS/collaborative_workflow#63]
**Title of section**
Naming conventions and file organization

**Suggested section content and location**
This might be documented within exiting sections instead - basically, giving instructions on how to organize code (e.g., should multiple R functions be placed in the same .R file? How do you decide whether to add to an existing file vs. create a new one?)

**Additional context**

A common convention with testthat files is to give them the same name as R function files with the prefix test- . For example, if myutils.R contains the R code, then the testthat functions that test the code would be in a file called test-myutils.R (in the tests/testthat subdir). I think this could be helpful for FIMS given so many will be touching the codebase, and may need to troubleshoot tests they did not write.

I'm also wondering if we could do something similar with the googletest tests and benchmarks, to make it easier to match up tests with the files that produced them? 

Open to other organizational ideas, though! I think whatever is decided on, it would be great to document it in the handbook.

**Comment by k-doering-NOAA** [comment]
[Guidance from r pkgs](https://r-pkgs.org/code.html#sec-code-organising)

In the interest of making a quick decision (that we can refactor in a future quality milestone), I propose:

- We try to group functions and their helpers together (the "main function plus helpers" approach)
- we ALWAYS name the test file the same as the R file, but with test- prepended (ex, test-myfunction.R contains testthat tests for the R code in R/myfunction.R)

**Comment by k-doering-NOAA** [comment]
Thanks @msupernaw for pointing out that it's the rcpp interface code that is using test that!

I took a look to see if there was a standard for naming rcpp files in other packages that use rcpp, but I couldn't find anything documented or any consistent practices.

I propose testthat tests that are a test of rcpp be called "test-rcpp-[something]" so that we can quickly identify that they are not associated with an R script. @kellijohnson-NOAA, do you feel like we should discuss this convention idea in the r interface group?

**Comment by kellijohnson-NOAA** [comment]
@k-doering-NOAA I think that your proposal is great and that we do not need to discuss it further within the R interface group. If anyone within FIMS thinks that we should do something different, feel free to comment on this issue by one week from tomorrow.
In the mean time,
@k-doering-NOAA do you have time to
- [ ] open a branch named rcpp-test-file in FIMS
- [ ] rename the test in rcpp-test-file
@iantaylor-NOAA do you have time to
- [ ] document how to name rcpp test files

Then, if there are no objections we can merge those branches into the main branches on May 08, 2024 at the end of the day.

**Comment by k-doering-NOAA** [comment]
Done with first 2 checklist items in https://github.com/NOAA-FIMS/FIMS/pull/571. I also realized we needed a naming convention for integration tests (which currently does not have a corresponding .R file), so used the convention `test-integration-description.R`

@iantaylor-NOAA, let me know if you are ok doing the documentation or if you would like me to.

**Comment by iantaylor-NOAA** [comment]
Boxes are all checked, but this issue should remain open until @kellijohnson-NOAA reviews https://github.com/NOAA-FIMS/FIMS/pull/571 and it gets merged on May 8 (unless you want to do so sooner).
