### ISSUE TITLE
Update or replace instructions about rendering the bookdown files?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [NOAA-FIMS/collaborative_workflow#68]
Thanks to #52 (implemented in #66), contributors to the workflow doc will be able to view the HTML book as an artifact of github actions rather than rendering the bookdown files locally. If that seems to be working well, we should update or replace the majority of Chapter 1, which is about rendering and previewing the book locally: https://noaa-fims.github.io/collaborative_workflow/index.html#render-book.

I didn't use the "Handbook addition" issue template because I'm not suggesting a `[NEW SECTION]` as would appear on the subject. Should we could we make a "Handbook edit" template for suggested changes to existing sections?

**Comment by ChristineStawitz-NOAA** [comment]
So I'm trying to understand the change we just made with the new workflow to document in the bookdown rendering instructions that are in `index.Rmd`. I will add you and Kathryn as reviewers to check !

**Comment by ChristineStawitz-NOAA** [comment]
I violated my own workflow and checked the changes directly into main. Please reopen if I'm wrong!
