### ISSUE TITLE
Create a handbook with best practices

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [NOAA-FIMS/collaborative_workflow#7]
The [TTS Handbook](https://handbook.tts.gsa.gov/) (available at [18F/handbook](https://github.com/18F/handbook)) is a good example of a government agency trying to document guidance on appropriate ways to collaborate and use tools.

**Comment by ChristineStawitz-NOAA** [comment]
see  https://noaa-fims.github.io/collaborative_workflow/
