### ISSUE TITLE
[BUG] dev workflow should include a note to run `styler` and `roxygenize` locally before submitting

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/collaborative_workflow#79]
**Describe the bug**
There has been some back and forth about whether styling and documentation should be done before pushing commits up or rely on the github actions to do it for you. I think in the interest of minimizing teh number of pull requests hanging open due to documentation, we agreed to ask the developer to do it and add to both the pull request template and the workflow doc here: https://github.com/NOAA-FIMS/FIMS/issues/55

These steps should be added to the doc.

I will try to add this but tagging Bai and Kathryn to be sure I captured the ideas correctly.

**Comment by Bai-Li-NOAA** [comment]
I worked on the same issue simultaneously with you!  Please feel free to add commits to this pull request #80
