### ISSUE TITLE
Document branch protection rules

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [NOAA-FIMS/collaborative_workflow#8]
[Branch protection](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule) allows for searching branch names with `grep` functionality to apply merging rules, i.e., protection. This will be helpful to protect the main/trunk branch such that pull requests cannot be merged in prior to passing various checks or by individuals without the authority to do so.

**Comment by kristanblackhart-NOAA** [comment]
Added into the code review section.
