### ISSUE TITLE
[NEW SECTION]: Information for developers on github actions

### ISSUE THREAD

**Issue by k-doering-NOAA** [NOAA-FIMS/collaborative_workflow#81]
**Title of section**
What should the new section you would like be called?
Github Actions

**Suggested section content and location**
What should this new section contain, and where should it be stored in the table of contents?
TBD based on discussion with the team, but perhaps include:
- what are github actions (link to github documentation on gha)
- where the code for github actions is located
- how to check the status of github actions associated with a commit or PR.
- suggested steps for debugging broken jobs 

**Additional context**
@Bai-Li-NOAA (or anyone else!) feel free to edit this comment or add your own thoughts on this thread!

**Comment by k-doering-NOAA** [comment]
@Bai-Li-NOAA , do you have time to put together a first draft of this? If not, I can put together a draft, but I probably won't have a first draft until the end of next week.

The [agenda from yesterday's FIMS meeting](https://docs.google.com/document/d/1y0obPXCUj3Gn1jJ_n8vcbe1qeQ_u9oM1v6RVWptY6aU/edit#heading=h.gwaeqesrwa9) has some other thoughts on what documentation is needed.

**Comment by Bai-Li-NOAA** [comment]
@k-doering-NOAA, I am counting hypothetical fish populations for the rest of this week and next week. Please feel free to start drafting the handbook and tag me for any writing tasks. I will catch up with you by the end of next week. Thanks!

**Comment by k-doering-NOAA** [comment]
@Bai-Li-NOAA, sounds good, will do!
