### ISSUE TITLE
[NEW SECTION] common C++ terms in the glossary

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/collaborative_workflow#82]
**Title of section**
C++ programming terminology

**Suggested section content and location**
Under Glossary, this should include code terminology that may not be apparent to new C++ programmers but comes up a lot in comments, issues, etc.
- [x] singleton
- [x] class
- [x] functor
- [x] constructor
- [x] destructor
- [x] header guards
- [x] preprocessing macro
- [x] struct

**Additional context**
Came up in selectivity group - good suggestion by @EJDick-NOAA

**Comment by k-doering-NOAA** [comment]
@msupernaw I added some basic definitions in links in 8495cd7. Can you check for accuracy and edit anything that I got wrong? Then, this issue can be closed.

**Comment by msupernaw** [comment]
A functor is a class that acts like a function.

**Comment by k-doering-NOAA** [comment]
Thanks!
