### ISSUE TITLE
FIMS logo without white background

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [NOAA-FIMS/collaborative_workflow#88]
**Is your feature request related to a problem? Please describe.**
When referencing the FIMS logo from https://raw.githubusercontent.com/NOAA-FIMS/collaborative_workflow/main/logo.png I get an image that has a white background rather than a clean hexagon.
![image](https://user-images.githubusercontent.com/4108564/168696202-21dd6e22-ebf6-4d84-8da7-c1e3650d74a4.png)

**Describe the solution you'd like**
I would like to know where to go to download a high resolution version of the logo that can be placed on a dark background that is in the shape of a hexagon rather than a hexagon on a square white background.

**Describe alternatives you've considered**
I can crop it myself, save it, and upload it to my own github user content, but then others would have to do the same thing. I think that we should add the hexagon or R code to make the hexagon in the FIMS package.

**Comment by iantaylor-NOAA** [comment]
Good idea.
I love the logo, but looking at it full size in the file linked on this issue, I see for the first time that the fish body is made up of the letters FIMS, which might be easier to see if it were higher resolution.

@kristanblackhart-NOAA can fill us in, but it doesn't look like it was made with R, which raises the question of whether it's worth somehow trying to replicate it in R. Whatever we choose, it may be worth creating image files in a few formats, similar to what NOAA has here: https://drive.google.com/drive/folders/17QrjaWNvm4Tfhd3JdML6Kc2r8px4VE1O.

**Comment by kristanblackhart-NOAA** [comment]
Attached are PNG versions of the final version of the logo (as hex logo, and without hex). These should be of sufficient resolution for various uses, and both have transparent backgrounds. If necessary, I can provide in other image formats. For reference, this was not made in R (although I think the version Kelli referenced above may have been Christine's attempt to replicate that process). 

![FIMS_logo3](https://user-images.githubusercontent.com/89920963/169611944-58afe18c-130a-48f7-a4ec-1dc247539466.png)
![FIMS_hexlogo](https://user-images.githubusercontent.com/89920963/169611948-ec184e03-d8a9-4e6e-863a-11ec89565386.png)

**Comment by kristanblackhart-NOAA** [comment]
Drag and drop for the image files didn't work properly. I've placed them in a subfolder of our FIMS google folder: https://drive.google.com/drive/folders/1vg5vo1SLIjKN22lT1aqW7C7lhXpdTHKm

**Comment by PatrickLynch-NOAA** [comment]
Slick...it took me a while to realize that the fish is made of FIMS...very nice! Maybe we should have called it the Fisheries Independent Software Home (FISH). (there's gotta be a better word for the H)

**Comment by kristanblackhart-NOAA** [comment]
hub

**Comment by PatrickLynch-NOAA** [comment]
You did it!

**Comment by kristanblackhart-NOAA** [comment]
yep, I'm a genius.

p.s. We're not changing the name. I'm not good at photoshop and the logo was a lot of work to make.

**Comment by k-doering-NOAA** [comment]
It looks great @kristanblackhart-NOAA ! :)

**Comment by kellijohnson-NOAA** [comment]
Thanks @kristanblackhart-NOAA

**Comment by iantaylor-NOAA** [comment]
@PatrickLynch-NOAA, not that you need more convincing, but note that searching for "FIMS stock assessment" (and similar) will work a lot better than "FISH stock assessment".
