### ISSUE TITLE
add in code style and notation guidelines to developer handbook

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/collaborative_workflow#9]
- log vs ln?
- tidyverse style guide?
- Google C++ style guide

**Comment by kristanblackhart-NOAA** [comment]
log vs. ln?

**Comment by kristanblackhart-NOAA** [comment]
Chapter 3 on style guide is complete unless you see the need for additions. I included Google C++ style guide and Google's R style guide (instead of tidyverse), but the latter can be reverted if there is disagreement.
