### ISSUE TITLE
Line breaks leads to broken code in handbook

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [NOAA-FIMS/collaborative_workflow#90]
Line breaks added in 25a98ae64d07aec049d70ee70dc09b6c8865a999 lead to broken R code because specifications for a chunk need to be on one line. The compiled html looks like this
![image](https://user-images.githubusercontent.com/4108564/169949451-cdcf4314-ee7e-4c87-8acc-88c94c140e0d.png)

There could be more instances of this behavior, I haven't checked the entire website. Here are some examples ...

https://github.com/NOAA-FIMS/collaborative_workflow/blob/25a98ae64d07aec049d70ee70dc09b6c8865a999/02-FIMS-Project-Overview.Rmd#L138-L140

https://github.com/NOAA-FIMS/collaborative_workflow/blob/e10c02148ec9fdd363befab295828a5659807e97/06-developer-software-guide.Rmd#L53-L54

**Comment by k-doering-NOAA** [comment]
I searched for ``` in the repo and the two instances you found were the only ones with this issue - thanks for pointing it out! Closing, since fixed in a7f919d
