### ISSUE TITLE
[NEW SECTION] how to setup cmake and ninja on github codespaces

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/collaborative_workflow#93]
**Title of section**
What should the new section you would like be called?

**Suggested section content and location**
What should this new section contain, and where should it be stored in the table of contents?

**Additional context**

**Comment by k-doering-NOAA** [comment]
@ChristineStawitz-NOAA this seems in your wheelhouse, time permitting.

**Comment by ChristineStawitz-NOAA** [comment]
Thanks @k-doering-NOAA ! I opened this thinking everyone would need to install the tools themselves on the codespace, before I realized I could pre-install it on the Docker image.

Do you think it's still worth having this section for future reference? If not, I can just close it and maybe add a section to the handbook on how to start codespaces?

**Comment by k-doering-NOAA** [comment]
Just adding a section (or link to GitHub documentation) on how to use codespaces seems good to me!

**Comment by kellijohnson-NOAA** [comment]
@k-doering-NOAA would you be willing to add a link somewhere to the GitHub documentation for how to use codespaces? If yes, please remove Christine and assign yourself to this issue.
