### ISSUE TITLE
Update documentation for recruitment module

### ISSUE THREAD

**Issue by Bai-Li-NOAA** [NOAA-FIMS/collaborative_workflow#94]
**Is your feature request related to a problem? Please describe.**
The FIMS recruitment module has been updated. We need to update [documentation for the recruitment module](https://noaa-fims.github.io/collaborative_workflow/m1-model-specification.html#beverton-holt-expected-recruitment-function) in the Developer Handbook once we merge the recruitment module pull request to the main branch. 

**Describe the solution you'd like**

- [x] Change bias adjustment factor $b_{y}$ to $b_{t}$ 
- [x] Add a section to document the likelihood component from recruitment_base.hpp

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by k-doering-NOAA** [comment]
@KyleShertzer-NOAA I see this was assigned some time ago to you. Are you still able to work on it?

**Comment by KyleShertzer-NOAA** [comment]
Yes. Thanks for the nudge.

**Comment by KyleShertzer-NOAA** [comment]
Full revision to the Beverton-Holt recruitment description.  Added recruitment deviations to the "Likelihood calculations" section.
